version: "3.9"

services:
  testing_mysql:
    container_name: testing_mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init_db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql_data/:/var/lib/mysql
